services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PWD}",
        "--maxmemory",
        "${REDIS_MAXMEMORY}",
        "--maxmemory-policy",
        "${REDIS_MAXMEMORY_POLICY}",
      ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PWD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_MAXMEMORY: ${REDIS_MAXMEMORY}
      REDIS_MAXMEMORY_POLICY: ${REDIS_MAXMEMORY_POLICY}

volumes:
  postgresql_data:
  redis_data:
